routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Clear Config cache:
Route::get('/clear', 'CacheController@clear')->name('clear');
Route::get('/cache', 'CacheController@cache')->name('cache');

Route::get('/', 'SiteController@index')->name('homepage');
Route::get('/home', 'SiteController@index')->name('home');
Route::get('/about', 'SiteController@about')->name('about');
Route::get('/blog', 'SiteController@blog')->name('blog');
Route::get('/causes', 'SiteController@causes')->name('causes');
Route::get('/contact', 'SiteController@contact')->name('contact');
Route::post('/contact', 'SiteController@contactUs')->name('contactus');
Route::get('/don', 'SiteController@donate')->name('don');
Route::get('/event', 'SiteController@event')->name('event');
Route::get('/gallery', 'SiteController@gallery')->name('gallery');

Route::group(['prefix'=>'admin'], function(){
    Route::group(['middleware'=>'auth'], function(){
       // Route::resource('sites', 'Admin\\SitesController');
        Route::resource('cause', 'Admin\\CauseController');
        Route::resource('don', 'Admin\\DonController');
        Route::resource('evenement', 'Admin\\EvenementController');
        Route::resource('image-gallerie', 'Admin\\ImageGallerieController');
        Route::resource('page-accueil', 'Admin\\PageAccueilController');
        Route::resource('page-a-propos', 'Admin\\PageAProposController');
        Route::resource('page-blog', 'Admin\\PageBlogController');
        Route::resource('page-blog-detail', 'Admin\\PageBlogDetailController');
        Route::resource('page-causes', 'Admin\\PageCausesController');
        Route::resource('page-causes-detail', 'Admin\\PageCausesDetailController');
        Route::resource('page-donation', 'Admin\\PageDonationController');
        Route::resource('page-event', 'Admin\\PageEventController');
        Route::resource('page-gallerie', 'Admin\\PageGallerieController');
        Route::resource('post', 'Admin\\PostController');
        Route::resource('site', 'Admin\\SitesController');
    });
    Route::get('/', 'Auth\\LoginController@showLoginForm')->name('admin_home');
     Auth::routes();
});

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')
            {!! csrf_field() !!}

        </div>
    </div>
@endsection

resources/views/admin/sidebar.blade.php
<div class="col-md-3">
    <div class="card">
        <div class="card-header">
            Menu
        </div>

        <div class="card-body pd-r-0 pd-t-0">
            <li class="as-nav @if(request()->routeIs('site*')) as-active @endif"
                role="presentation">
                <a href="{{ route('site.index') }}">
                    Infos générales
                </a>
            </li>
            <ul class="nav" role="tablist">
                <li class="as-nav @if(request()->routeIs('page-accueil*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-accueil.edit', 1) }}">
                        Page Accueil
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-a-propos*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-a-propos.edit', 1) }}">
                        Page à propos
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-causes.edit')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-causes.edit', 1) }}">
                        Page Causes
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-causes-detail*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-causes-detail.edit', 1) }}">
                        page causes detail
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-donation*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-donation.edit', 1) }}">
                        page donation
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-blog.index') || request()->routeIs('site.index')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-blog.edit', 1) }}">
                        Page Blog
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-blog-detail*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-blog-detail.edit', 1) }}">
                        Page Blog détails
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-gallerie*')) as-active @endif"
                    role="presentation" class="mg-r-70 mg-t-10">
                    <a href="{{ route('page-gallerie.edit', 1) }}">
                        page gallerie
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('page-event*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('page-event.edit', 1) }}">
                        page évènement
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('image-gallerie*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('image-gallerie.index') }}">
                        Galleries
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('cause*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('cause.index') }}">
                        Causes
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('post*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('post.index') }}">
                        Mon Blog
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('don*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('don.index') }}">
                        Don
                    </a>
                </li>
                <li class="as-nav @if(request()->routeIs('evenement*')) as-active @endif"
                    role="presentation">
                    <a href="{{ route('evenement.index') }}">
                        Evènement
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>